version: "3.9"
services:
  customerpostgres:
    container_name: customer-postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bcbpZBQ08yQ=
      - POSTGRES_DB=customerdb
    ports:
      - "5433:5433"
    command: -p 5433
    expose:
      - 5433
  customerserver:
    container_name: customer-server
    build: .
    ports:
      - "1100:1100"
    links:
      - customerpostgres
    command: -p 1100
    expose:
      - 1100
    env_file:
      - .env