version: "3.9"
services:
  customerpostgres:
    container_name: customer-postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${CUSTOMER_POSTGRES_USER}
      - POSTGRES_PASSWORD=${CUSTOMER_POSTGRES_PASSWORD}
      - POSTGRES_DB=customerdb
    ports:
      - ${CUSTOMER_POSTGRES_PORT}:${CUSTOMER_POSTGRES_PORT}
    env_file:
      - .env
    command: -p ${CUSTOMER_POSTGRES_PORT}
    expose:
      - ${CUSTOMER_POSTGRES_PORT}
  customerserver:
    container_name: customer-server
    build: .
    ports:
      - ${CUSTOMER_RMI_PORT}:${CUSTOMER_RMI_PORT}
    links:
      - customerpostgres
    env_file:
      - .env
    command: -p ${CUSTOMER_RMI_PORT}
    expose:
      - ${CUSTOMER_RMI_PORT}